/* eslint-disable */
// Generated by Wrangler by running `wrangler types --path=./worker-configuration.d.ts` (hash: 4ef061814ecbdb87ba26a14ab2164b10)
// Runtime types generated with workerd@1.20260515.1 2026-08-09 nodejs_compat
interface __BaseEnv_Env {
	PUBLIC_INQUIRY_RATE_LIMITER: RateLimit;
	PUBLIC_INQUIRY_GLOBAL_RATE_LIMITER: RateLimit;
	VITE_SUPABASE_URL: "https://gmtdqeskyvdvyibccxwt.supabase.co";
	VITE_SUPABASE_PUBLISHABLE_KEY: "sb_publishable_RdT2JC1U6Im3VKobzFzTjg_hy-SWjJo";
	SUPABASE_URL: "https://gmtdqeskyvdvyibccxwt.supabase.co";
	SUPABASE_PUBLISHABLE_KEY: "sb_publishable_RdT2JC1U6Im3VKobzFzTjg_hy-SWjJo";
	CLOUDINARY_CLOUD_NAME: "lkln9llc";
	CLOUDINARY_API_KEY: "144277162759167";
	CLOUDINARY_UPLOAD_PRESET: "rupantar_works_signed";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VITE_SUPABASE_URL" | "VITE_SUPABASE_PUBLISHABLE_KEY" | "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY" | "CLOUDINARY_CLOUD_NAME" | "CLOUDINARY_API_KEY" | "CLOUDINARY_UPLOAD_PRESET">> {}
}

// Begin runtime types
/*! *****************************************************************************
Copyright (c) Cloudflare. All rights reserved.
Copyright (c) Microsoft Corporation. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0
THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.
See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */
/* eslint-disable */
// noinspection JSUnusedGlobalSymbols
declare var onmessage: never;
/**
 * The **`DOMException`** interface represents an abnormal event (called an **exception**) that occurs as a result of calling a method or accessing a property of a web API.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMException)
 */
declare class DOMException extends Error {
    constructor(message?: string, name?: string);
    /**
     * The **`message`** read-only property of the a message or description associated with the given error name.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMException/message)
     */
    readonly message: string;
    /**
     * The **`name`** read-only property of the one of the strings associated with an error name.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMException/name)
     */
    readonly name: string;
    /**
     * The **`code`** read-only property of the DOMException interface returns one of the legacy error code constants, or `0` if none match.
     * @deprecated
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMException/code)
     */
    readonly code: number;
    static readonly INDEX_SIZE_ERR: number;
    static readonly DOMSTRING_SIZE_ERR: number;
    static readonly HIERARCHY_REQUEST_ERR: number;
    static readonly WRONG_DOCUMENT_ERR: number;
    static readonly INVALID_CHARACTER_ERR: number;
    static readonly NO_DATA_ALLOWED_ERR: number;
    static readonly NO_MODIFICATION_ALLOWED_ERR: number;
    static readonly NOT_FOUND_ERR: number;
    static readonly NOT_SUPPORTED_ERR: number;
    static readonly INUSE_ATTRIBUTE_ERR: number;
    static readonly INVALID_STATE_ERR: number;
    static readonly SYNTAX_ERR: number;
    static readonly INVALID_MODIFICATION_ERR: number;
    static readonly NAMESPACE_ERR: number;
    static readonly INVALID_ACCESS_ERR: number;
    static readonly VALIDATION_ERR: number;
    static readonly TYPE_MISMATCH_ERR: number;
    static readonly SECURITY_ERR: number;
    static readonly NETWORK_ERR: number;
    static readonly ABORT_ERR: number;
    static readonly URL_MISMATCH_ERR: number;
    static readonly QUOTA_EXCEEDED_ERR: number;
    static readonly TIMEOUT_ERR: number;
    static readonly INVALID_NODE_TYPE_ERR: number;
    static readonly DATA_CLONE_ERR: number;
    get stack(): any;
    set stack(value: any);
}
type WorkerGlobalScopeEventMap = {
    fetch: FetchEvent;
    scheduled: ScheduledEvent;
    queue: QueueEvent;
    unhandledrejection: PromiseRejectionEvent;
    rejectionhandled: PromiseRejectionEvent;
};
declare abstract class WorkerGlobalScope extends EventTarget<WorkerGlobalScopeEventMap> {
    EventTarget: typeof EventTarget;
}
/* The **`console`** object provides access to the debugging console (e.g., the Web console in Firefox). *
 * The **`console`** object provides access to the debugging console (e.g., the Web console in Firefox).
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/console)
 */
interface Console {
    "assert"(condition?: boolean, ...data: any[]): void;
    /**
     * The **`console.clear()`** static method clears the console if possible.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/clear_static)
     */
    clear(): void;
    /**
     * The **`console.count()`** static method logs the number of times that this particular call to `count()` has been called.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/count_static)
     */
    count(label?: string): void;
    /**
     * The **`console.countReset()`** static method resets counter used with console/count_static.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/countReset_static)
     */
    countReset(label?: string): void;
    /**
     * The **`console.debug()`** static method outputs a message to the console at the 'debug' log level.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/debug_static)
     */
    debug(...data: any[]): void;
    /**
     * The **`console.dir()`** static method displays a list of the properties of the specified JavaScript object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/dir_static)
     */
    dir(item?: any, options?: any): void;
    /**
     * The **`console.dirxml()`** static method displays an interactive tree of the descendant elements of the specified XML/HTML element.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/dirxml_static)
     */
    dirxml(...data: any[]): void;
    /**
     * The **`console.error()`** static method outputs a message to the console at the 'error' log level.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/error_static)
     */
    error(...data: any[]): void;
    /**
     * The **`console.group()`** static method creates a new inline group in the Web console log, causing any subsequent console messages to be indented by an additional level, until console/groupEnd_static is called.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/group_static)
     */
    group(...data: any[]): void;
    /**
     * The **`console.groupCollapsed()`** static method creates a new inline group in the console.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/groupCollapsed_static)
     */
    groupCollapsed(...data: any[]): void;
    /**
     * The **`console.groupEnd()`** static method exits the current inline group in the console.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/groupEnd_static)
     */
    groupEnd(): void;
    /**
     * The **`console.info()`** static method outputs a message to the console at the 'info' log level.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/info_static)
     */
    info(...data: any[]): void;
    /**
     * The **`console.log()`** static method outputs a message to the console.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/log_static)
     */
    log(...data: any[]): void;
    /**
     * The **`console.table()`** static method displays tabular data as a table.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/table_static)
     */
    table(tabularData?: any, properties?: string[]): void;
    /**
     * The **`console.time()`** static method starts a timer you can use to track how long an operation takes.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/time_static)
     */
    time(label?: string): void;
    /**
     * The **`console.timeEnd()`** static method stops a timer that was previously started by calling console/time_static.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/timeEnd_static)
     */
    timeEnd(label?: string): void;
    /**
     * The **`console.timeLog()`** static method logs the current value of a timer that was previously started by calling console/time_static.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/timeLog_static)
     */
    timeLog(label?: string, ...data: any[]): void;
    timeStamp(label?: string): void;
    /**
     * The **`console.trace()`** static method outputs a stack trace to the console.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/trace_static)
     */
    trace(...data: any[]): void;
    /**
     * The **`console.warn()`** static method outputs a warning message to the console at the 'warning' log level.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/warn_static)
     */
    warn(...data: any[]): void;
}
declare const console: Console;
type BufferSource = ArrayBufferView | ArrayBuffer;
type TypedArray = Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array | BigInt64Array | BigUint64Array;
declare namespace WebAssembly {
    class CompileError extends Error {
        constructor(message?: string);
    }
    class RuntimeError extends Error {
        constructor(message?: string);
    }
    type ValueType = "anyfunc" | "externref" | "f32" | "f64" | "i32" | "i64" | "v128";
    interface GlobalDescriptor {
        value: ValueType;
        mutable?: boolean;
    }
    class Global {
        constructor(descriptor: GlobalDescriptor, value?: any);
        value: any;
        valueOf(): any;
    }
    type ImportValue = ExportValue | number;
    type ModuleImports = Record<string, ImportValue>;
    type Imports = Record<string, ModuleImports>;
    type ExportValue = Function | Global | Memory | Table;
    type Exports = Record<string, ExportValue>;
    class Instance {
        constructor(module: Module, imports?: Imports);
        readonly exports: Exports;
    }
    interface MemoryDescriptor {
        initial: number;
        maximum?: number;
        shared?: boolean;
    }
    class Memory {
        constructor(descriptor: MemoryDescriptor);
        readonly buffer: ArrayBuffer;
        grow(delta: number): number;
    }
    type ImportExportKind = "function" | "global" | "memory" | "table";
    interface ModuleExportDescriptor {
        kind: ImportExportKind;
        name: string;
    }
    interface ModuleImportDescriptor {
        kind: ImportExportKind;
        module: string;
        name: string;
    }
    abstract class Module {
        static customSections(module: Module, sectionName: string): ArrayBuffer[];
        static exports(module: Module): ModuleExportDescriptor[];
        static imports(module: Module): ModuleImportDescriptor[];
    }
    type TableKind = "anyfunc" | "externref";
    interface TableDescriptor {
        element: TableKind;
        initial: number;
        maximum?: number;
    }
    class Table {
        constructor(descriptor: TableDescriptor, value?: any);
        readonly length: number;
        get(index: number): any;
        grow(delta: number, value?: any): number;
        set(index: number, value?: any): void;
    }
    function instantiate(module: Module, imports?: Imports): Promise<Instance>;
    function validate(bytes: BufferSource): boolean;
}
/**
 * The **`ServiceWorkerGlobalScope`** interface of the Service Worker API represents the global execution context of a service worker.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ServiceWorkerGlobalScope)
 */
interface ServiceWorkerGlobalScope extends WorkerGlobalScope {
    DOMException: typeof DOMException;
    WorkerGlobalScope: typeof WorkerGlobalScope;
    btoa(data: string): string;
    atob(data: string): string;
    setTimeout(callback: (...args: any[]) => void, msDelay?: number): number;
    setTimeout<Args extends any[]>(callback: (...args: Args) => void, msDelay?: number, ...args: Args): number;
    clearTimeout(timeoutId: number | null): void;
    setInterval(callback: (...args: any[]) => void, msDelay?: number): number;
    setInterval<Args extends any[]>(callback: (...args: Args) => void, msDelay?: number, ...args: Args): number;
    clearInterval(timeoutId: number | null): void;
    queueMicrotask(task: Function): void;
    structuredClone<T>(value: T, options?: StructuredSerializeOptions): T;
    reportError(error: any): void;
    fetch(input: RequestInfo | URL, init?: RequestInit<RequestInitCfProperties>): Promise<Response>;
    self: ServiceWorkerGlobalScope;
    crypto: Crypto;
    caches: CacheStorage;
    scheduler: Scheduler;
    performance: Performance;
    Cloudflare: Cloudflare;
    readonly origin: string;
    Event: typeof Event;
    ExtendableEvent: typeof ExtendableEvent;
    CustomEvent: typeof CustomEvent;
    PromiseRejectionEvent: typeof PromiseRejectionEvent;
    FetchEvent: typeof FetchEvent;
    TailEvent: typeof TailEvent;
    TraceEvent: typeof TailEvent;
    ScheduledEvent: typeof ScheduledEvent;
    MessageEvent: typeof MessageEvent;
    CloseEvent: typeof CloseEvent;
    ReadableStreamDefaultReader: typeof ReadableStreamDefaultReader;
    ReadableStreamBYOBReader: typeof ReadableStreamBYOBReader;
    ReadableStream: typeof ReadableStream;
    WritableStream: typeof WritableStream;
    WritableStreamDefaultWriter: typeof WritableStreamDefaultWriter;
    TransformStream: typeof TransformStream;
    ByteLengthQueuingStrategy: typeof ByteLengthQueuingStrategy;
    CountQueuingStrategy: typeof CountQueuingStrategy;
    ErrorEvent: typeof ErrorEvent;
    MessageChannel: typeof MessageChannel;
    MessagePort: typeof MessagePort;
    EventSource: typeof EventSource;
    ReadableStreamBYOBRequest: typeof ReadableStr×Ÿ{çkh‘éì¶»§q«^uH™XİÜˆ™]\›ˆÙ]ˆ\È]™[Ùˆ™]šY]˜[\È™œ™YHˆ[ˆ]›ÈY][Û˜[İ™\šXY\È[˜İ\œ™Y™]\›š[™È\È]KˆİÙ]™\‹›İH][™^YY]Y]H\ÈİXš™XİÈ[˜Ø][Ûˆ
\ÜXÚX[H›Üˆ\™Ù\ˆİš[™ÜÊK‚ˆ
ˆ›Ü\H›Û™H›È[™^YY]Y]HÚ[™H™]\›™Y‚ˆ
‹Â\H™XİÜš^™SY]Y]T™]šY]˜[]™[H˜[ˆš[™^Yˆ››Û™HÂš[\™˜XÙH™XİÜš^™T]Y\SÜ[ÛœÈÂˆÜÏÎˆ[X™\Âˆ˜[Y\ÜXÙOÎˆİš[™ÎÂˆ™]\›•˜[Y\ÏÎˆ›ÛÛX[Âˆ™]\›“Y]Y]OÎˆ›ÛÛX[ˆ™XİÜš^™SY]Y]T™]šY]˜[]™[Âˆš[\Îˆ™XİÜš^™U™XİÜ“Y]Y]Qš[\ÂŸB‹ÊŠ‚ˆ
ˆ[™›Ü›X][ÛˆX›İ]HÛÛ™šYİ\˜][ÛˆÙˆ[ˆ[™^‚ˆ
‹Â\H™XİÜš^™R[™^ÛÛ™šYÈHÂˆ[Y[œÚ[ÛœÎˆ[X™\ÂˆY]šXÎˆ™XİÜš^™Q\İ[˜ÙSY]šXÎÂŸHÂˆ™\Ù]ˆİš[™ÎÈËÈÙY\\ÈÙ[™\šXË\ÈÙIÛ™HY[™È[Ü™H™\Ù]È[ˆH]\™H[™\È\ÈÛ›H[ˆH™XYØ\XÚ]BŸNÂ‹ÊŠ‚ˆ
ˆY]Y]HX›İ][ˆ^\İ[™È[™^‚ˆ
‚ˆ
ˆ\È\H\È^Û\Ú]™[H›ÜˆH™XİÜš^™H
Š˜™]JŠˆ[™Ú[™H\™XØ]YÛ˜ÙH™XİÜš^™HÈ\È™[X\ÙY‚ˆ
ˆÙYHĞ[šÈ™XİÜš^™R[™^[™›ßH›Üˆ]ÈÜİX™]H\]Z]˜[[‚ˆ
‹Âš[\™˜XÙH™XİÜš^™R[™^]Z[ÈÂˆÊŠˆH[š\]YHQÙˆH[™^
‹Âˆ™XYÛ›HYˆİš[™ÎÂˆÊŠˆH˜[YHÙˆH[™^ˆ
‹Âˆ˜[YNˆİš[™ÎÂˆÊŠˆ
Ü[Û˜[
HH[X[ˆ™XYX›H\ØÜš\[Ûˆ›ÜˆH[™^ˆ
‹Âˆ\ØÜš\[ÛÎˆİš[™ÎÂˆÊŠˆH[™^ÛÛ™šYİ\˜][Û‹[˜ÛY[™ÈH[Y[œÚ[ÛˆÚ^™H[™\İ[˜ÙHY]šXËˆ
‹ÂˆÛÛ™šYÎˆ™XİÜš^™R[™^ÛÛ™šYÎÂˆÊŠˆH[X™\ˆÙˆ™XÛÜ™ÈÛÛZ[š[™È™XİÜœÈÚ][ˆH[™^ˆ
‹Âˆ™XİÜœĞÛİ[ˆ[X™\ÂŸB‹ÊŠ‚ˆ
ˆY]Y]HX›İ][ˆ^\İ[™È[™^‚ˆ
‹Âš[\™˜XÙH™XİÜš^™R[™^[™›ÈÂˆÊŠˆH[X™\ˆÙˆ™XÛÜ™ÈÛÛZ[š[™È™XİÜœÈÚ][ˆH[™^ˆ
‹Âˆ™XİÜÛİ[ˆ[X™\ÂˆÊŠˆ[X™\ˆÙˆ[Y[œÚ[ÛœÈH[™^\È™Y[ˆÛÛ™šYİ\™Y›Ü‹ˆ
‹Âˆ[Y[œÚ[ÛœÎˆ[X™\ÂˆÊŠˆTÓÈŒH]][YHÙˆH\İ›ØÙ\ÜÙY]]][ÛˆÛˆ[ˆH[™^ˆ[Ú[™Ù\È™Y›Ü™H\È]]][ÛˆÚ[™H™Y›XİY[ˆH[™^İ]Kˆ
‹Âˆ›ØÙ\ÜÙY\Ñ]][YNˆ[X™\ÂˆÊŠˆURQÙˆH\İ]]][Ûˆ›ØÙ\ÜÙYHH[™^ˆ[Ú[™Ù\È™Y›Ü™H\È]]][ÛˆÚ[™H™Y›XİY[ˆH[™^İ]Kˆ
‹Âˆ›ØÙ\ÜÙY\Ó]]][Ûˆ[X™\ÂŸB‹ÊŠ‚ˆ
ˆ™\™\Ù[ÈHÚ[™ÛH™XİÜˆ˜[YHÙ][Û™ÈÚ]]È\ÜÛØÚX]YY]Y]K‚ˆ
‹Âš[\™˜XÙH™XİÜš^™U™XİÜˆÂˆÊŠˆHQ›ÜˆH™XİÜ‹ˆ\ÈØ[ˆ™H\Ù\‹YYš[™Y[™]\İ™H[š\]YKˆ]Úİ[[š\]Y[HY[YHHØš™Xİ[™\È™\İÙ]˜\ÙYÛˆHQÙˆÚ]H™XİÜˆ™\™\Ù[Ëˆ
‹ÂˆYˆİš[™ÎÂˆÊŠˆH™XİÜˆ˜[Y\È
‹Âˆ˜[Y\Îˆ™XİÜ‘›Ø]\œ˜^H[X™\–×NÂˆÊŠˆH˜[Y\ÜXÙH\È™XİÜˆ™[Û™ÜÈËˆ
‹Âˆ˜[Y\ÜXÙOÎˆİš[™ÎÂˆÊŠˆY]Y]H\ÜÛØÚX]YÚ]H™XİÜ‹ˆ[˜ÛY\ÈH˜[Y\ÈÙˆİ\ˆšY[È[™İ[X[HY][Û˜[]Z[Ëˆ
‹ÂˆY]Y]OÎˆ™XÛÜ™İš[™Ë™XİÜš^™U™XİÜ“Y]Y]OÂŸB‹ÊŠ‚ˆ
ˆ™\™\Ù[ÈHX]ÚY™XİÜˆ›ÜˆH]Y\H[Û™ÈÚ]]ÈØÛÜ™H[™
YˆÜXÚYšYY
HHX]Ú[™È™XİÜˆ[™›Ü›X][Û‹‚ˆ
‹Â\H™XİÜš^™SX]ÚHXÚÏ\X[™XİÜš^™U™XİÜ‹˜[Y\Èˆ	ˆÛZ]™XİÜš^™U™XİÜ‹˜[Y\Èˆ	ˆÂˆÊŠˆHØÛÜ™HÜˆ˜[šÈ›ÜˆÚ[Z[\š]KÚ[ˆ™]\›™Y\ÈH™\İ[
‹ÂˆØÛÜ™Nˆ[X™\ÂŸNÂ‹ÊŠ‚ˆ
ˆHÙ]ÙˆX]Ú[™ÈĞ[šÈ™XİÜš^™SX]ÚH›ÜˆH\Xİ[\ˆ]Y\K‚ˆ
‹Âš[\™˜XÙH™XİÜš^™SX]Ú\ÈÂˆX]Ú\Îˆ™XİÜš^™SX]Ú×NÂˆÛİ[ˆ[X™\ÂŸB‹ÊŠ‚ˆ
ˆ™\İ[ÈÙˆ[ˆÜ\˜][Ûˆ]\™›Ü›YYH]]][ÛˆÛˆHÙ]Ùˆ™XİÜœË‚ˆ
ˆ\™KYØ\ÈH\İÙˆ™XİÜœÈ]Ù\™HİXØÙ\ÜÙ[H›ØÙ\ÜÙY‚ˆ
‚ˆ
ˆ\È\H\È^Û\Ú]™[H›ÜˆH™XİÜš^™H
Š˜™]JŠˆ[™Ú[™H\™XØ]YÛ˜ÙH™XİÜš^™HÈ\È™[X\ÙY‚ˆ
ˆÙYHĞ[šÈ™XİÜš^™P\Ş[˜Ó]]][ÛŸH›Üˆ]ÈÜİX™]H\]Z]˜[[‚ˆ
‹Âš[\™˜XÙH™XİÜš^™U™XİÜ“]]][ÛˆÂˆÊˆ\İÙˆYÈÙˆ™XİÜœÈ]Ù\™HİXØÙ\ÜÙ[H›ØÙ\ÜÙYˆ
‹ÂˆYÎˆİš[™Ö×NÂˆÊˆİ[Ûİ[ÙˆH[X™\ˆÙˆ›ØÙ\ÜÙY™XİÜœËˆ
‹ÂˆÛİ[ˆ[X™\ÂŸB‹ÊŠ‚ˆ
ˆ™\İ[\H[™XØ][™ÈH]]][ÛˆÛˆH™XİÜš^™H[™^‚ˆ
ˆXİX[]]][ÛœÈ\™H›ØÙ\ÜÙY\Ş[˜ÈÚ\™HH]]][Û’Y\ÈH[š\]YHY[YšY\ˆ›ÜˆHÜ\˜][Û‹‚ˆ
‹Âš[\™˜XÙH™XİÜš^™P\Ş[˜Ó]]][ÛˆÂˆÊŠˆH[š\]YHY[YšY\ˆ›ÜˆH\Ş[˜È]]][ÛˆÜ\˜][ÛˆÛÛZ[š[™ÈHÚ[™Ù\Ù]ˆ
‹Âˆ]]][Û’Yˆİš[™ÎÂŸB‹ÊŠ‚ˆ
ˆH™XİÜš^™H™XİÜˆÙX\˜Ú[™^›Üˆ]Y\Z[™È™XİÜœËÙ[X™Y[™ÜË‚ˆ
‚ˆ
ˆ\È\H\È^Û\Ú]™[H›ÜˆH™XİÜš^™H
Š˜™]JŠˆ[™Ú[™H\™XØ]YÛ˜ÙH™XİÜš^™HÈ\È™[X\ÙY‚ˆ
ˆÙYHĞ[šÈ™XİÜš^™_H›Üˆ]È™]È[\[Y[][Û‹‚ˆ
‹Â™XÛ\™HXœİ˜XİÛ\ÜÈ™XİÜš^™R[™^ÂˆÊŠ‚ˆ
ˆÙ][™›Ü›X][ÛˆX›İ]Hİ\œ™[H›İ[™[™^‚ˆ
ˆ™]\›œÈH›ÛZ\ÙH]™\ÛÛ™\ÈÚ][™›Ü›X][ÛˆX›İ]Hİ\œ™[[™^‚ˆ
‹ÂˆX›XÈ\ØÜšX™J
Nˆ›ÛZ\ÙO™XİÜš^™R[™^]Z[ÏÂˆÊŠ‚ˆ
ˆ\ÙHH›İšYY™XİÜˆÈ\™›Ü›HHÚ[Z[\š]HÙX\˜ÚXÜ›ÜÜÈH[™^‚ˆ
ˆ\˜[H™XİÜˆ[œ]™XİÜˆ]Ú[™H\ÙYÈš]™HHÚ[Z[\š]HÙX\˜Ú‚ˆ
ˆ\˜[HÜ[ÛœÈÛÛ™šYİ\˜][ÛˆÜ[ÛœÈÈX\ÜØYÙHH™]\›™Y]K‚ˆ
ˆ™]\›œÈH›ÛZ\ÙH]™\ÛÛ™\ÈÚ]X]ÚY[™ØÛÜ™Y™XİÜœË‚ˆ
‹ÂˆX›XÈ]Y\J™XİÜˆ™XİÜ‘›Ø]\œ˜^H[X™\–×KÜ[ÛœÏÎˆ™XİÜš^™T]Y\SÜ[ÛœÊNˆ›ÛZ\ÙO™XİÜš^™SX]Ú\ÏÂˆÊŠ‚ˆ
ˆ[œÙ\H\İÙˆ™XİÜœÈ[ÈH[™^]\Ù]ˆYˆH›İšYYY^\İË[ˆ\œ›ÜˆÚ[™H›İÛ‹‚ˆ
ˆ\˜[H™XİÜœÈ\İÙˆ™XİÜœÈ]Ú[™H[œÙ\Y‚ˆ
ˆ™]\›œÈH›ÛZ\ÙH]™\ÛÛ™\ÈÚ]HYÈ	ˆÛİ[Ùˆ™XÛÜ™È]Ù\™HİXØÙ\ÜÙ[H›ØÙ\ÜÙY‚ˆ
‹ÂˆX›XÈ[œÙ\
™XİÜœÎˆ™XİÜš^™U™XİÜ–×JNˆ›ÛZ\ÙO™XİÜš^™U™XİÜ“]]][ÛÂˆÊŠ‚ˆ
ˆ\Ù\H\İÙˆ™XİÜœÈ[ÈH[™^]\Ù]ˆYˆH›İšYYY^\İË]Ú[™H™\XÙYÚ]H™]È˜[Y\Ë‚ˆ
ˆ\˜[H™XİÜœÈ\İÙˆ™XİÜœÈ]Ú[™H\Ù\Y‚ˆ
ˆ™]\›œÈH›ÛZ\ÙH]™\ÛÛ™\ÈÚ]HYÈ	ˆÛİ[Ùˆ™XÛÜ™È]Ù\™HİXØÙ\ÜÙ[H›ØÙ\ÜÙY‚ˆ
‹ÂˆX›XÈ\Ù\
™XİÜœÎˆ™XİÜš^™U™XİÜ–×JNˆ›ÛZ\ÙO™XİÜš^™U™XİÜ“]]][ÛÂˆÊŠ‚ˆ
ˆ[]HH\İÙˆ™XİÜœÈÚ]HX]Ú[™ÈY‚ˆ
ˆ\˜[HYÈ\İÙˆ™XİÜˆYÈ]Úİ[™H[]Y‚ˆ
ˆ™]\›œÈH›ÛZ\ÙH]™\ÛÛ™\ÈÚ]HYÈ	ˆÛİ[Ùˆ™XÛÜ™È]Ù\™HİXØÙ\ÜÙ[H›ØÙ\ÜÙY
[™\È[]Y
K‚ˆ
‹ÂˆX›XÈ[]PRYÊYÎˆİš[™Ö×JNˆ›ÛZ\ÙO™XİÜš^™U™XİÜ“]]][ÛÂˆÊŠ‚ˆ
ˆÙ]H\İÙˆ™XİÜœÈÚ]HX]Ú[™ÈY‚ˆ
ˆ\˜[HYÈ\İÙˆ™XİÜˆYÈ]Úİ[™H™]\›™Y‚ˆ
ˆ™]\›œÈH›ÛZ\ÙH]™\ÛÛ™\ÈÚ]H˜]È[œØÛÜ™Y™XİÜœÈX]Ú[™ÈHYÙ]‚ˆ
‹ÂˆX›XÈÙ]RYÊYÎˆİš[™Ö×JNˆ›ÛZ\ÙO™XİÜš^™U™XİÜ–×OÂŸB‹ÊŠ‚ˆ
ˆH™XİÜš^™H™XİÜˆÙX\˜Ú[™^›Üˆ]Y\Z[™È™XİÜœËÙ[X™Y[™ÜË‚ˆ
‚ˆ
ˆ]]][ÛœÈ[ˆ\È™\œÚ[Ûˆ\™H\Ş[˜Ë™]\›š[™ÈH]]][ÛˆY‚ˆ
‹Â™XÛ\™HXœİ˜XİÛ\ÜÈ™XİÜš^™HÂˆÊŠ‚ˆ
ˆÙ][™›Ü›X][ÛˆX›İ]Hİ\œ™[H›İ[™[™^‚ˆ
ˆ™]\›œÈH›ÛZ\ÙH]™\ÛÛ™\ÈÚ][™›Ü›X][ÛˆX›İ]Hİ\œ™[[™^‚ˆ
‹ÂˆX›XÈ\ØÜšX™J
Nˆ›ÛZ\ÙO™XİÜš^™R[™^[™›ÏÂˆÊŠ‚ˆ
ˆ\ÙHH›İšYY™XİÜˆÈ\™›Ü›HHÚ[Z[\š]HÙX\˜ÚXÜ›ÜÜÈH[™^‚ˆ
ˆ\˜[H™XİÜˆ[œ]™XİÜˆ]Ú[™H\ÙYÈš]™HHÚ[Z[\š]HÙX\˜Ú‚ˆ
ˆ\˜[HÜ[ÛœÈÛÛ™šYİ\˜][ÛˆÜ[ÛœÈÈX\ÜØYÙHH™]\›™Y]K‚ˆ
ˆ™]\›œÈH›ÛZ\ÙH]™\ÛÛ™\ÈÚ]X]ÚY[™ØÛÜ™Y™XİÜœË‚ˆ
‹ÂˆX›XÈ]Y\J™XİÜˆ™XİÜ‘›Ø]\œ˜^H[X™\–×KÜ[ÛœÏÎˆ™XİÜš^™T]Y\SÜ[ÛœÊNˆ›ÛZ\ÙO™XİÜš^™SX]Ú\ÏÂˆÊŠ‚ˆ
ˆ\ÙHH›İšYY™XİÜ‹ZYÈ\™›Ü›HHÚ[Z[\š]HÙX\˜ÚXÜ›ÜÜÈH[™^‚ˆ
ˆ\˜[H™XİÜ’YY›ÜˆH™XİÜˆ[ˆH[™^YØZ[œİÚXÚH[™^Úİ[™H]Y\šYY‚ˆ
ˆ\˜[HÜ[ÛœÈÛÛ™šYİ\˜][ÛˆÜ[ÛœÈÈX\ÜØYÙHH™]\›™Y]K‚ˆ
ˆ™]\›œÈH›ÛZ\ÙH]™\ÛÛ™\ÈÚ]X]ÚY[™ØÛÜ™Y™XİÜœË‚ˆ
‹ÂˆX›XÈ]Y\PRY
™XİÜ’Yˆİš[™ËÜ[ÛœÏÎˆ™XİÜš^™T]Y\SÜ[ÛœÊNˆ›ÛZ\ÙO™XİÜš^™SX]Ú\ÏÂˆÊŠ‚ˆ
ˆ[œÙ\H\İÙˆ™XİÜœÈ[ÈH[™^]\Ù]ˆYˆH›İšYYY^\İË[ˆ\œ›ÜˆÚ[™H›İÛ‹‚ˆ
ˆ\˜[H™XİÜœÈ\İÙˆ™XİÜœÈ]Ú[™H[œÙ\Y‚ˆ
ˆ™]\›œÈH›ÛZ\ÙH]™\ÛÛ™\ÈÚ]H[š\]YHY[YšY\ˆÙˆH]]][ÛˆÛÛZ[š[™ÈH[œÙ\Ú[™Ù\Ù]‚ˆ
‹ÂˆX›XÈ[œÙ\
™XİÜœÎˆ™XİÜš^™U™XİÜ–×JNˆ›ÛZ\ÙO™XİÜš^™P\Ş[˜Ó]]][ÛÂˆÊŠ‚ˆ
ˆ\Ù\H\İÙˆ™XİÜœÈ[ÈH[™^]\Ù]ˆYˆH›İšYYY^\İË]Ú[™H™\XÙYÚ]H™]È˜[Y\Ë‚ˆ
ˆ\˜[H™XİÜœÈ\İÙˆ™XİÜœÈ]Ú[™H\Ù\Y‚ˆ
ˆ™]\›œÈH›ÛZ\ÙH]™\ÛÛ™\ÈÚ]H[š\]YHY[YšY\ˆÙˆH]]][ÛˆÛÛZ[š[™ÈH\Ù\Ú[™Ù\Ù]‚ˆ
‹ÂˆX›XÈ\Ù\
™XİÜœÎˆ™XİÜš^™U™XİÜ–×JNˆ›ÛZ\ÙO™XİÜš^™P\Ş[˜Ó]]][ÛÂˆÊŠ‚ˆ
ˆ[]HH\İÙˆ™XİÜœÈÚ]HX]Ú[™ÈY‚ˆ
ˆ\˜[HYÈ\İÙˆ™XİÜˆYÈ]Úİ[™H[]Y‚ˆ
ˆ™]\›œÈH›ÛZ\ÙH]™\ÛÛ™\ÈÚ]H[š\]YHY[YšY\ˆÙˆH]]][ÛˆÛÛZ[š[™ÈH[]HÚ[™Ù\Ù]‚ˆ
‹ÂˆX›XÈ[]PRYÊYÎˆİš[™Ö×JNˆ›ÛZ\ÙO™XİÜš^™P\Ş[˜Ó]]][ÛÂˆÊŠ‚ˆ
ˆÙ]H\İÙˆ™XİÜœÈÚ]HX]Ú[™ÈY‚ˆ
ˆ\˜[HYÈ\İÙˆ™XİÜˆYÈ]Úİ[™H™]\›™Y‚ˆ
ˆ™]\›œÈH›ÛZ\ÙH]™\ÛÛ™\ÈÚ]H˜]È[œØÛÜ™Y™XİÜœÈX]Ú[™ÈHYÙ]‚ˆ
‹ÂˆX›XÈÙ]RYÊYÎˆİš[™Ö×JNˆ›ÛZ\ÙO™XİÜš^™U™XİÜ–×OÂŸB‹ÊŠ‚ˆ
ˆH[\™˜XÙH›Üˆ™\œÚ[Û—ÛY]Y]Hˆš[™[™Âˆ
ˆ›İšY[™ÈY]Y]HX›İ]HÛÜšÙ\ˆ™\œÚ[Ûˆ\Ú[™È\Èš[™[™Ë‚ˆ
‹Â\HÛÜšÙ\•™\œÚ[Û“Y]Y]HHÂˆÊŠˆHQÙˆHÛÜšÙ\ˆ™\œÚ[Ûˆ\Ú[™È\Èš[™[™È
‹ÂˆYˆİš[™ÎÂˆÊŠˆHYÈÙˆHÛÜšÙ\ˆ™\œÚ[Ûˆ\Ú[™È\Èš[™[™È
‹ÂˆYÎˆİš[™ÎÂˆÊŠˆH[Y\İ[\ÙˆÚ[ˆHÛÜšÙ\ˆ™\œÚ[ÛˆØ\È\ØYY
‹Âˆ[Y\İ[\ˆİš[™ÎÂŸNÂš[\™˜XÙH[˜[ZXÑ\Ü]Ú[Z]ÈÂˆÊŠ‚ˆ
ˆ[Z]ÔH[YH[ˆZ[\ÙXÛÛ™Ë‚ˆ
‹ÂˆÜS\ÏÎˆ[X™\ÂˆÊŠ‚ˆ
ˆ[Z][X™\ˆÙˆİXœ™\]Y\İË‚ˆ
‹ÂˆİX”™\]Y\İÏÎˆ[X™\ÂŸBš[\™˜XÙH[˜[ZXÑ\Ü]ÚÜ[ÛœÈÂˆÊŠ‚ˆ
ˆ[Z]™\Ûİ\˜Ù\ÈÙˆ[›ÚÙYÛÜšÙ\ˆØÜš\‚ˆ
‹Âˆ[Z]ÏÎˆ[˜[ZXÑ\Ü]Ú[Z]ÎÂˆÊŠ‚ˆ
ˆ\™İ[Y[È›Üˆİ]›İ[™ÛÜšÙ\ˆØÜš\YˆÛÛ™šYİ\™Y‚ˆ
‹Âˆİ]›İ[™ÎˆÂˆÚÙ^Nˆİš[™×Nˆ[NÂˆNÂŸBš[\™˜XÙH\Ü]Ú˜[Y\ÜXÙHÂˆÊŠ‚ˆ
ˆ\˜[H˜[YH˜[YHÙˆHÛÜšÙ\ˆØÜš\‚ˆ
ˆ\˜[H\™ÜÈ\™İ[Y[ÈÈÛÜšÙ\ˆØÜš\‚ˆ
ˆ\˜[HÜ[ÛœÈÜ[ÛœÈ›Üˆ[˜[ZXÈ\Ü]Ú[›ØØ][Û‹‚ˆ
ˆ™]\›œÈH™]Ú\ˆØš™Xİ][İÜÈ[İHÈÙ[™™\]Y\İÈÈHÛÜšÙ\ˆØÜš\‚ˆ
ˆ›İÜÈYˆHÛÜšÙ\ˆØÜš\Ù\È›İ^\İ[ˆ\È\Ü]Ú˜[Y\ÜXÙK[ˆ\œ›ÜˆÚ[™H›İÛ‹‚ˆ
‹ÂˆÙ]
˜[YNˆİš[™Ë\™ÜÏÎˆÂˆÚÙ^Nˆİš[™×Nˆ[NÂˆKÜ[ÛœÏÎˆ[˜[ZXÑ\Ü]ÚÜ[ÛœÊNˆ™]Ú\ÂŸB™XÛ\™H[Ù[H	ØÛİY›\™NÛÜšÙ›İÜÉÈÂˆÊŠ‚ˆ
ˆ›Û”™]XX›Q\œ›Üˆ[İÜÈ›ÜˆH\Ù\ˆÈ›İÈH˜][\œ›Ü‚ˆ
ˆ]XZÙ\ÈHÛÜšÙ›İÈ[œİ[˜ÙH˜Z[[[YYX][HÚ]İ]šYÙÙ\š[™ÈH™]Bˆ
‹Âˆ^ÜÛ\ÜÈ›Û”™]XX›Q\œ›Üˆ^[™È\œ›ÜˆÂˆX›XÈÛÛœİXİÜŠY\ÜØYÙNˆİš[™Ë˜[YOÎˆİš[™ÊNÂˆBŸB™XÛ\™HXœİ˜XİÛ\ÜÈÛÜšÙ›İÏTSTÈH[šÛ›İÛˆÂˆÊŠ‚ˆ
ˆÙ]H[™HÈ[ˆ^\İ[™È[œİ[˜ÙHÙˆHÛÜšÙ›İË‚ˆ
ˆ\˜[HYY›ÜˆH[œİ[˜ÙHÙˆ\ÈÛÜšÙ›İÂˆ
ˆ™]\›œÈH›ÛZ\ÙH]™\ÛÛ™\ÈÚ]H[™H›ÜˆH[œİ[˜ÙBˆ
‹ÂˆX›XÈÙ]
Yˆİš[™ÊNˆ›ÛZ\ÙOÛÜšÙ›İÒ[œİ[˜ÙOÂˆÊŠ‚ˆ
ˆÜ™X]HH™]È[œİ[˜ÙH[™™]\›ˆH[™HÈ]ˆYˆH›İšYYY^\İË[ˆ\œ›ÜˆÚ[™H›İÛ‹‚ˆ
ˆ\˜[HÜ[ÛœÈÜ[ÛœÈÚ[ˆÜ™X][™È[ˆ[œİ[˜ÙH[˜ÛY[™ÈY[™\˜[\Âˆ
ˆ™]\›œÈH›ÛZ\ÙH]™\ÛÛ™\ÈÚ]H[™H›ÜˆH[œİ[˜ÙBˆ
‹ÂˆX›XÈÜ™X]JÜ[ÛœÏÎˆÛÜšÙ›İÒ[œİ[˜ÙPÜ™X]SÜ[ÛœÏTSTÏŠNˆ›ÛZ\ÙOÛÜšÙ›İÒ[œİ[˜ÙOÂˆÊŠ‚ˆ
ˆÜ™X]HH˜]ÚÙˆ[œİ[˜Ù\È[™™]\›ˆ[™H›Üˆ[Ùˆ[KˆYˆH›İšYYY^\İË[ˆ\œ›ÜˆÚ[™H›İÛ‹‚ˆ
ˆÜ™X]P˜]Ú\È[Z]Y]L[œİ[˜Ù\È]H[YHÜˆÚ[ˆH”È[Z]›ÜˆH˜]Ú
SZPŠH\È™XXÚY‚ˆ
ˆ\˜[H˜]Ú\İÙˆÜ[ÛœÈÚ[ˆÜ™X][™È[ˆ[œİ[˜ÙH[˜ÛY[™È˜[YH[™\˜[\Âˆ
ˆ™]\›œÈH›ÛZ\ÙH]™\ÛÛ™\ÈÚ]H\İÙˆ[™\È›ÜˆHÜ™X]Y[œİ[˜Ù\Ë‚ˆ
‹ÂˆX›XÈÜ™X]P˜]Ú
˜]ÚˆÛÜšÙ›İÒ[œİ[˜ÙPÜ™X]SÜ[ÛœÏTSTÏ–×JNˆ›ÛZ\ÙOÛÜšÙ›İÒ[œİ[˜ÙV×OÂŸB\HÛÜšÙ›İÑ\˜][Û“X™[H	ÜÙXÛÛ™	È	ÛZ[]IÈ	Úİ\‰È	Ù^IÈ	İÙYZÉÈ	Û[Û	È	ŞYX\‰ÎÂ\HÛÜšÙ›İÔÛY\\˜][ÛˆH	Û[X™\ŸH	ÕÛÜšÙ›İÑ\˜][Û“X™[IÉÜÉÈ	ÉßX[X™\Â\HÛÜšÙ›İÔ™][[Û‘\˜][ÛˆHÛÜšÙ›İÔÛY\\˜][ÛÂš[\™˜XÙHÛÜšÙ›İÒ[œİ[˜ÙPÜ™X]SÜ[ÛœÏTSTÈH[šÛ›İÛˆÂˆÊŠ‚ˆ
ˆ[ˆY›Üˆ[İ\ˆÛÜšÙ›İÈ[œİ[˜ÙKˆ]\İ™H[š\]YHÚ][ˆHÛÜšÙ›İË‚ˆ
‹ÂˆYÎˆİš[™ÎÂˆÊŠ‚ˆ
ˆH]™[^[ØYHÛÜšÙ›İÈ[œİ[˜ÙH\ÈšYÙÙ\™YÚ]ˆ
‹Âˆ\˜[\ÏÎˆTSTÎÂˆÊŠ‚ˆ
ˆH™][[ÛˆÛXŞH›ÜˆÛÜšÙ›İÈ[œİ[˜ÙK‚ˆ
ˆY˜][ÈÈHX^[][H™][[Ûˆ\š[Ù]˜Z[X›H›ÜˆHİÛ™\‰ÜÈXØÛİ[‚ˆ
‹Âˆ™][[ÛÎˆÂˆİXØÙ\ÜÔ™][[ÛÎˆÛÜšÙ›İÔ™][[Û‘\˜][ÛÂˆ\œ›Ü”™][[ÛÎˆÛÜšÙ›İÔ™][[Û‘\˜][ÛÂˆNÂŸB\H[œİ[˜ÙTİ]\ÈHÂˆİ]\Îˆ	Ü]Y]YY	ÈËÈYX[œÈ][œİ[˜ÙH\ÈØZ][™ÈÈ™Hİ\Y
ÙYHÛÛ˜İ\œ™[˜ŞH[Z]ÊBˆ	Ü[›š[™ÉÈ	Ü]\ÙY	È	Ù\œ›Ü™Y	È	İ\›Z[˜]Y	ÈËÈ\Ù\ˆ\›Z[˜]YH[œİ[˜ÙHÚ[H]Ø\È[›š[™Âˆ	ØÛÛ\]IÈ	İØZ][™ÉÈËÈ[œİ[˜ÙH\ÈX™\›˜][™È[™ØZ][™È›ÜˆÛY\Üˆ]™[Èš[š\Úˆ	İØZ][™Ñ›Ü”]\ÙIÈËÈ[œİ[˜ÙH\Èš[š\Ú[™ÈHİ\œ™[ÛÜšÈÈ]\ÙBˆ	İ[šÛ›İÛ‰ÎÂˆ\œ›ÜÎˆÂˆ˜[YNˆİš[™ÎÂˆY\ÜØYÙNˆİš[™ÎÂˆNÂˆİ]]Îˆ[šÛ›İÛÂŸNÂš[\™˜XÙHÛÜšÙ›İÑ\œ›ÜˆÂˆÛÙOÎˆ[X™\ÂˆY\ÜØYÙNˆİš[™ÎÂŸBš[\™˜XÙHÛÜšÙ›İÒ[œİ[˜ÙT™\İ\Ü[ÛœÈÂˆÊŠ‚ˆ
ˆ™\İ\œ›ÛHHÜXÚYšXÈİ\ˆYˆÛZ]YH[œİ[˜ÙH™\İ\Èœ›ÛHH™YÚ[›š[™Ë‚ˆ
ˆHİ\]\İ^\İ[ˆH[œİ[˜ÙIÜÈ^Xİ][Ûˆ\İÜK‚ˆ
‹Âˆœ›ÛOÎˆÂˆÊŠ‚ˆ
ˆHİ\˜[YH\ÈYš[™Y[ˆ[İ\ˆÛÜšÙ›İÈÛÙK‚ˆ
‹Âˆ˜[YNˆİš[™ÎÂˆÊŠ‚ˆ
ˆKZ[™^YØØİ\œ™[˜ÙHÙˆ\Èİ\˜[YKˆ\ÙHÚ[ˆHØ[YHİ\˜[YH\X\œÈ][\H[Y\È
K™Ëˆ[ˆHÛÜ
K‚ˆ
ˆY˜][Bˆ
‹ÂˆÛİ[Îˆ[X™\ÂˆÊŠ‚ˆ
ˆİ\\Hš[\‹ˆ\ÙHÚ[ˆY™™\™[İ\\\ÈÚ\™HHØ[YH˜[YK‚ˆ
‹Âˆ\OÎˆ	ÙÉÈ	ÜÛY\	È	İØZ]›Ü‘]™[	ÎÂˆNÂŸB™XÛ\™HXœİ˜XİÛ\ÜÈÛÜšÙ›İÒ[œİ[˜ÙHÂˆX›XÈYˆİš[™ÎÂˆÊŠ‚ˆ
ˆ]\ÙHH[œİ[˜ÙK‚ˆ
‹ÂˆX›XÈ]\ÙJ
Nˆ›ÛZ\ÙO›ÚYÂˆÊŠ‚ˆ
ˆ™\İ[YHH[œİ[˜ÙKˆYˆ]\È[™XYH[›š[™Ë[ˆ\œ›ÜˆÚ[™H›İÛ‹‚ˆ
‹ÂˆX›XÈ™\İ[YJ
Nˆ›ÛZ\ÙO›ÚYÂˆÊŠ‚ˆ
ˆ\›Z[˜]HH[œİ[˜ÙKˆYˆ]\È\œ›Ü™Y\›Z[˜]YÜˆÛÛ\]K[ˆ\œ›ÜˆÚ[™H›İÛ‹‚ˆ
‹ÂˆX›XÈ\›Z[˜]J
Nˆ›ÛZ\ÙO›ÚYÂˆÊŠ‚ˆ
ˆ™\İ\H[œİ[˜ÙKˆÜ[Û˜[H™\İ\œ›ÛHHÜXÚYšXÈİ\™\Ù\š[™Âˆ
ˆØXÚY™\İ[È›Üˆ[İ\È™Y›Ü™H]‚ˆ
ˆ\˜[HÜ[ÛœÈÜ[ÛœÈ›ÜˆH™\İ\[˜ÛY[™È[ˆÜ[Û˜[İ\È™\İ\œ›ÛK‚ˆ
‹ÂˆX›XÈ™\İ\
Ü[ÛœÏÎˆÛÜšÙ›İÒ[œİ[˜ÙT™\İ\Ü[ÛœÊNˆ›ÛZ\ÙO›ÚYÂˆÊŠ‚ˆ
ˆ™]\›œÈHİ\œ™[İ]\ÈÙˆH[œİ[˜ÙK‚ˆ
‹ÂˆX›XÈİ]\Ê
Nˆ›ÛZ\ÙO[œİ[˜ÙTİ]\ÏÂˆÊŠ‚ˆ
ˆÙ[™[ˆ]™[È\È[œİ[˜ÙK‚ˆ
‹ÂˆX›XÈÙ[™]™[
È\K^[ØYNˆÂˆ\Nˆİš[™ÎÂˆ^[ØYˆ[šÛ›İÛÂˆJNˆ›ÛZ\ÙO›ÚYÂŸB